export const GET_DELEVERY_SCHEDULE = 'GET_DELEVERY_SCHEDULE';
export const GET_DELEVERY_SCHEDULE_SUCCESS = 'GET_DELEVERY_SCHEDULE_SUCCESS';
export const GET_DELEVERY_SCHEDULE_FAILED = 'GET_DELEVERY_SCHEDULE_FAILED';
export const GET_DELEVERY_SCHEDULE_API_URL = 'https://localhost:44301/Scheduler';